# -*- coding: utf-8 -*-
"""SALES_ANALYSIS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LduIloZRUWe2yTNnDerU8-ZE-5PnPMxG
"""

# Import libraries
import matplotlib.pyplot as plt

# -------------------------------
# Data for MAE Comparison (Bar Chart)
# -------------------------------
models = ['Linear Regression', 'ARIMA', 'Random Forest', 'LSTM', 'XGBoost']
mae_values = [0.82, 1.01, 0.65, 0.60, 0.52]

# -------------------------------
# Data for Accuracy Comparison (Line Chart)
# -------------------------------
algorithms = ['ARIMA', 'Linear Regression', 'SVM', 'Decision Tree', 'Random Forest', 'LSTM']
accuracy = [68, 72, 78, 75, 85, 88]

# -------------------------------
# Create Figure with 2 Plots
# -------------------------------
plt.figure(figsize=(14, 6))

# -------- Bar Chart --------
plt.subplot(1, 2, 1)
plt.bar(models, mae_values)
plt.title('MAE Comparison of Sales Forecasting Models')
plt.xlabel('Forecasting Models')
plt.ylabel('Mean Absolute Error (MAE)')
plt.xticks(rotation=30)

# -------- Line Chart --------
plt.subplot(1, 2, 2)
plt.plot(algorithms, accuracy, marker='o')
plt.title('Accuracy Comparison of Sales Forecasting Algorithms')
plt.xlabel('Forecasting Algorithms')
plt.ylabel('Accuracy (%)')
plt.xticks(rotation=30)

# Layout fix
plt.tight_layout()

# Show plots
plt.show()

# Install seaborn (if not already)
!pip install seaborn

# Import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# -------------------------------
# Create Sample Data (like your image)
# -------------------------------
dates = pd.date_range(start='2025-02-01', end='2025-03-31', freq='7D')
status = ['Pending', 'Cancelled', 'Payment Completed', 'Product Sale']

# Generate heatmap values (order count)
np.random.seed(0)
data = np.random.randint(200, 1800, size=(len(status), len(dates)))

df = pd.DataFrame(data, index=status, columns=dates)

# -------------------------------
# Plot Heatmap
# -------------------------------
plt.figure(figsize=(12, 6))

sns.heatmap(df, cmap="YlOrRd", linewidths=0.5, linecolor='white', cbar_kws={'label': 'Order Count'})

# -------------------------------
# Add Trend Lines (overlay)
# -------------------------------
for i in range(len(status)):
    plt.plot(np.arange(len(dates)) + 0.5,
             [i + 0.5]*len(dates),
             marker='o', linewidth=1)

# -------------------------------
# Labels & Title
# -------------------------------
plt.title('Retail Sales & Order Status Trends (2025)')
plt.xlabel('Date (2025)')
plt.ylabel('Order Status')

# Format x-axis labels
plt.xticks(ticks=np.arange(len(dates)) + 0.5,
           labels=[d.strftime('%b %d') for d in dates],
           rotation=30)

plt.yticks(rotation=0)

plt.tight_layout()
plt.show()